#!/bin/bash

# check if other instances are running & terminate them
for pid in `pidof -x "dual_monitor_nitrogen"`;
	do
		if [[ $pid -ne $$ ]]; then
			kill $pid;
		fi
	done

# check if connected to internet
ping -q -c 1 -W 1 google.com > /dev/null 2>&1

if [ $? -ne 0 ]; then
	echo "No internet connection." 2>&1

	exit;
fi

while [ true ]
do
	# check if 1 monitor is connected
	if [[ $(xrandr | grep -wc connected) -le 1 ]]; then
		if [[ $(gsettings get org.nemo.desktop show-desktop-icons) -eq false ]]; then
			gsettings set org.nemo.desktop show-desktop-icons true;
		fi
		
nitrogen --set-zoom --random;

		sleep 5m;
		continue 2;
	fi

	# 2 monitors; need to disable show desktop icons for nitrogen to work
	if [[ $(xrandr | grep -wc connected) -eq 2 ]]; then
		if [[ $(gsettings get org.nemo.desktop show-desktop-icons) -eq true ]]; then
			gsettings set org.nemo.desktop show-desktop-icons false;
		fi
		
nitrogen --set-zoom --random;
	
		sleep 5m;
		continue 2;
	fi
done
